version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/static:/app/frontend/static
      - ./frontend/package.json:/app/frontend/package.json
      - ./frontend/svelte.config.js:/app/frontend/svelte.config.js
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
      - ./shared:/app/shared
    environment:
      VITE_PUBLIC_BACKEND_URL: http://localhost:3001
      INTERNAL_BACKEND_URL: http://backend:3001
    depends_on:
      - backend
    networks:
      - jspulse-net

  mongo:
    image: mongo:latest
    container_name: jspulse-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - jspulse-net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/jspulse
      PORT: "3001"
    networks:
      - jspulse-net

networks:
  jspulse-net:
    driver: bridge

volumes:
  mongodb_data:
