version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/static:/app/frontend/static
      - ./frontend/package.json:/app/frontend/package.json
      - ./frontend/svelte.config.js:/app/frontend/svelte.config.js
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
      # - ./frontend/tsconfig.json:/app/frontend/tsconfig.json # Раскомментировать, если есть
      - ./shared:/app/shared
    environment:
      - VITE_BACKEND_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend/package.json:/app/backend/package.json
      - ./shared:/app/shared
    environment:
      - MONGO_URL=mongodb://mongo:27017/jspulse
      - PORT=3001
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
