version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: jspulse_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  backend:
    build: ./backend
    container_name: jspulse_backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/jsjobs
      - PORT=3001

  frontend:
    build: ./frontend
    container_name: jspulse_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
