version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # Удаляем настройки аутентификации
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-stage
    ports:
      - "3001:3001"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/jspulse
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3001/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-stage
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - PORT=3000
      - NODE_ENV=development
      - ORIGIN=http://localhost:3000
      - VITE_PUBLIC_BACKEND_URL=http://localhost:3001
      - INTERNAL_BACKEND_URL=http://backend:3001

volumes:
  mongodb_data:
