version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/shared/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /app/backend/node_modules
      - /app/shared/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/jspulse
      - PORT=3001
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
